# Error Handling

2021년 7월 3주차

### 목차

1. [에러 표현 방식](#1-에러-표현-방식)
2. [에러 처리](#2-에러-처리)
3. [rethrow](#3-rethrow)
4. [defer](#4-defer)





## 1. 에러 표현 방식

: 타입이 `Error` protocol을 채택하여 오류를 표현할 수 있다


#### 1. Enum

- 오류의 종류를 표현하기에 적합함
- associated value를 사용하여 오류에 관한 부가 정보를 제공할 수 있음

```swift
enum ValidationError: Error {
    case tooShort
    case tooLong
    case invalidCharacterFound(Character)
}

func validate(username: String) throws {
    guard username.count > 4 else {
        throw ValidationError.tooShort
    }

    guard username.count < 11 else {
        throw ValidationError.tooLong
    }

    for character in username {
        guard character.isLetter else {
            throw ValidationError.invalidCharacterFound(character)
        }
    }
}

do {
    try validate(username: "Lia!!!")
} catch {
    print(error) // invalidCharacterFound("!")
}
```



#### 2. Struct / Class

> Error 타입 구분하기
```swift
struct CustomErrorStruct : Error {
    var message : String
}

class CustomErrorClass : Error { }


do {
    let error = CustomErrorStruct(message:"some error")
    throw error
} catch let error where error is CustomErrorStruct {
    print("error with Struct")
} catch let error where error is CustomErrorClass {
    print("eroor with Class")
} catch let error {
    print("unknown error", error)
}
```


> Xcode가 보여주는 error 와 비슷한 형태
```swift
struct XMLParsingError: Error {
   enum ErrorKind {
       case invalidCharacter
       case mismatchedTag
       case internalError
   }

   let line: Int
   let column: Int
   let kind: ErrorKind
}

func parse(_ source: String) throws -> XMLDoc {
   // ...
   throw XMLParsingError(line: 19, column: 5, kind: .mismatchedTag)
   // ...
}

do {
   let xmlDoc = try parse(myXMLData)
} catch let error as XMLParsingError {
   print("Parsing error: \(error.kind) [\(error.line):\(error.column)]")
} catch {
   print("Other error: \(error)")
}
// Prints "Parsing error: mismatchedTag [19:5]"
```



#### 3. LocalizedError

- Error protocol을 채택한 타입을 확장하여 `LocalizedError`을 채택하면 된다
- 원하는 에러 메시지 구현 가능

```swift
enum ValidationError: Error {
    case tooShort
    case tooLong
    case invalidCharacterFound(Character)
}

extension ValidationError: LocalizedError {
    var errorDescription: String? {
        switch self {
        case .tooShort:
            return NSLocalizedString(
                "Under length",
                comment: "Username needs to be at least 5 characters long"
            )
        case .tooLong:
            return NSLocalizedString(
                "Exceeding length",
                comment: "Username can't be longer than 10 characters"
            )
        case .invalidCharacterFound(let character):
            let format = NSLocalizedString(
                "Invalid character exception : '%@' contained",
                comment: "Username can't contain the character '%@'"
            )

            return String(format: format, String(character))
        }
    }
}

func validate(username: String) throws {
    guard username.count > 4 else {
        throw ValidationError.tooShort
    }

    guard username.count < 11 else {
        throw ValidationError.tooLong
    }

    for character in username {
        guard character.isLetter else {
            throw ValidationError.invalidCharacterFound(character)
        }
    }
}

do {
    try validate(username: "Lia!!!")
} catch {
    print(error.localizedDescription) // Invalid character exception : '!' contained
}
```



## 2. 에러 처리

#### 1. try, throw


```swift

```


#### 2. do - catch

```swift

```


#### 3. try? try!

```swift

```





## 3. rethrow

- `rethrow` 키워드를 통해, 매개변수로 받은 함수가 오류를 던진다는 것을 명시


#### 1. 사용법

```swift
func someThrowingFunc() throws {
  enum SomeError: Error {
    case justSomeError
  }
  
  throw SomeError.justSomeError
}

func someFunction(callback: () throws -> Void) rethrows {
  enum AnotherError: Error {
    case justAnotherError
  }
  
  do {
    try callback()
  } catch {
    throw AnotherError.justAnotherError
  }
  
  do {
    try someThrowingFunc()
  } catch {
    // 에러 발생!!
    throw AnotehrError.justAnotherError
  }
  
  // catch 절 외부에서 단독으로 오류 던질 수 없음
  // 에러 발생!!
  throw AnotherError.justAnotherError
}
```



#### 2. 상속에서 규칙

```swift

```





## 4. defer

- 현재 코드 블록을 나가기 전에 꼭 특정 코드를 실행해야 하는 경우 사용
- 에러 처리 외에도 사용될 수 있음



#### 1. 기본 사용법

- 실행 순서
  - 맨 마지막에 작성된 구문부터 역순으로 실행됨
  - 오류가 던져지면, 그 직전 defer 까지 실행됨
- defer 내부에는 break, return 같이 구문을 빠져나가는 코드나, 오류 던지는 코드를 작성해서는 안됨


```swift

```



#### 2. 에러 처리 시 사용법

- 주의 사항 : `throw`보다 앞에 작성해야 실행됨

```swift
func someThrowingFunction() throws {
    defer {
        print("finished")
    }
    throw CustomErrorStruct(message: "struct error~")
}

try someThrowingFunction()

// finished
// Swift/ErrorType.swift:200:
// Fatal error: Error raised at top level
// : study_swift.CustomErrorStruct(message: "struct error~")
```





### 출처
- 스위프트 프로그래밍 3판 (야곰 저)
- [`Validation` 예제 코드](https://www.hohyeonmoon.com/blog/swift-error-handling/) - Localized Error 포함
- [구조체 에러 예제 - Xcode 에러](https://rhino-developer.tistory.com/entry/Swift-ErrorHandling)
- [defer 참고 블로그](https://devmjun.github.io/archive/ErrorInSwift)

